config/routes.rb
Testapp::Application.routes.draw do

  resources :services

  resources :abouts

  resources :posts do
    resources :comments
    end

  resources :posts 

    resources :comments 

  resources :users 
 
  resources :testimonals
 
  get "home/index"
  

  root :to => 'home#index'

end

app/models/testimonal.rb
class Testimonal < ActiveRecord::Base
validates_format_of :name, :with => /^[a-zA-Z\d ]*$/i,:message =>
 "can only contain letters and numbers." 
end

app/controllers/testimonals_controller.rb
class TestimonalsController < ApplicationController
  # GET /testimonals
  # GET /testimonals.json
  def index
    @testimonals = Testimonal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testimonals }
    end
  end

  # GET /testimonals/1
  # GET /testimonals/1.json
  def show
    @testimonal = Testimonal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testimonal }
    end
  end

  # GET /testimonals/new
  # GET /testimonals/new.json
  def new
    @testimonal = Testimonal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testimonal }
    end
  end

  # GET /testimonals/1/edit
  def edit
    @testimonal = Testimonal.find(params[:id])
  end

  # POST /testimonals
  # POST /testimonals.json
  def create
    @testimonal = Testimonal.new(params[:testimonal])

    respond_to do |format|
      if @testimonal.save
        format.html { redirect_to @testimonal, notice: 'Testimonal was successfully created.' }
        format.json { render json: @testimonal, status: :created, location: @testimonal }
      else
        format.html { render action: "new" }
        format.json { render json: @testimonal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testimonals/1
  # PUT /testimonals/1.json
  def update
    @testimonal = Testimonal.find(params[:id])

    respond_to do |format|
      if @testimonal.update_attributes(params[:testimonal])
        format.html { redirect_to @testimonal, notice: 'Testimonal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @testimonal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonals/1
  # DELETE /testimonals/1.json
  def destroy
    @testimonal = Testimonal.find(params[:id])
    @testimonal.destroy

    respond_to do |format|
      format.html { redirect_to testimonals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/testimonals_helper.rb
module TestimonalsHelper
end

app/views/testimonals/_form.html.erb
<%= form_for(@testimonal) do |f| %>
  <% if @testimonal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonal.errors.count, "error") %> prohibited this testimonal from being saved:</h2>

      <ul>
      <% @testimonal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonals/edit.html.erb
<h1>Editing testimonal</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonal %> |
<%= link_to 'Back', testimonals_path %>

app/views/testimonals/index.html.erb
<h1>Listing testimonals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testimonals.each do |testimonal| %>
  <tr>
    <td><%= testimonal.name %></td>
    <td><%= testimonal.description %></td>
    <td><%= link_to 'Show', testimonal %></td>
    <td><%= link_to 'Edit', edit_testimonal_path(testimonal) %></td>
    <td><%= link_to 'Destroy', testimonal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Testimonal', new_testimonal_path %>

app/views/testimonals/new.html.erb
<h1>New testimonal</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonals_path %>

app/views/testimonals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @testimonal.name %>
</p>

<p>
  <b>Description:</b>
  <%= @testimonal.description %>
</p>


<%= link_to 'Edit', edit_testimonal_path(@testimonal) %> |
<%= link_to 'Back', testimonals_path %>