config/routes.rb
Testapp::Application.routes.draw do

  resources :services

  resources :abouts

  resources :posts do
    resources :comments
    end

  resources :posts 

    resources :comments 

  resources :users 
 
  resources :testimonals
 
  get "home/index"
  

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>

<div id="banner">

<%= image_tag("logo.png", :alt => "rss feed") %>
</div>
<div id="columns"></div>
<div id="side"></div>

<body style ="background-color:skyblue;">

<ul id="nav">
	<li> <%= link_to 'HOME',home_index_path  %> </li>
	<li> <%= link_to 'ABOUT US', abouts_path %> </li>
        <li> <%= link_to 'SERVICES', services_path  %> </li>
        <li> <%= link_to 'TESTIMONIALS', testimonals_path  %> </li>

	<li> <%= link_to 'BLOG', posts_path %> </li>
	<li> <%= link_to 'CONTACT US', new_user_path  %> </li>

</ul>
<%= yield %>
<div style="text-align: center; font-size: 0.75em;">

<div id="footer">


<%= link_to 'HOME', %> | <%= link_to 'ABOUT US', abouts_path %> | <%= link_to 'SERVICES',services_path  %> | <%= link_to 'TESTIMONIALS', testimonals_path %> |<%= link_to 'BLOG', posts_path %> | <%= link_to 'CONTACT US', new_user_path %>

 

 </div>



<b>Copyright &copy; 2012 ANIRA SOLUTIONS</b>
<br>


</div>
</div>
<div style="text-align: center; font-size: 0.75em;">
<b>Developed by
ANIRA SOLUTIONS.</b> 

</div>
</div>

</div>

</html>